export const RENDER_NOTE = 'RENDER_NOTE'
export const ADD_NOTE = 'ADD_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const UPDATE_NOTE = 'UPDATE_NOTE'
export const STAR_NOTE = 'STAR_NOTE'
export const GET_NOTELIST = 'GET_NOTELIST'
// export const TAG_NOTE = 'TAG_NOTE'
// export const GET_NOTE = 'GET_NOTE'
